production:
  sessions:
    default:
      database: todozen_production
      username: <%= ENV['MONGO_USERNAME'] %>
      password: <%= ENV['MONGO_PASSWORD'] %>
      hosts:
        - <%= ENV['MONGO_HOST'] %>
      options:
        consistency: :strong
  options:
    raise_not_found_error: false

development:
  sessions:
    default:
      database: todozen_development
      hosts:
        - 127.0.0.1:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: todozen_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong